- name: "Backend Setup"
  hosts: remote
  user: ubuntu


  roles:
    - configure-server


  environment:
    ENVIRONMENT=production
    TYPEORM_CONNECTION=postgres
    TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST=nanodegdb.c0low1hk4taw.us-west-2.rds.amazonaws.com
    TYPEORM_PORT=5432
    TYPEORM_USERNAME=nanoDegUser
    TYPEORM_PASSWORD=nanoDegUser
    TYPEORM_DATABASE=nanoDegDB
