version: 2.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello
          command: |
            echo "Hello World"

  #build phase
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: cd ./frontend && npm i && npm run build 

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: cd ./backend && npm i && npm run build

  #test phase
  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Frontend Test
          command: | 
            cd ./frontend && npm i
            npm install --save-dev jest-junit
            npm run test --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
              JEST_JUNIT_OUTPUT_DIR: ./test-results/jest/
      - store_test_results:
          path: ./frontend/test-results/jest/
      - store_artifacts:
          path: ./frontend/test-results/jest/
    

  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: 
          name: Backend Test
          command: |
            cd ./backend && npm i
            npm install --save-dev jest-junit
            npm run test --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
              JEST_JUNIT_OUTPUT_DIR: ./test-results/jest/
      - store_test_results:
          path: ./backend/test-results/jest/
      - store_artifacts:
          path: ./backend/test-results/jest/

workflows:
  default:
    jobs:
      - hello-world
      - build-frontend
      - build-backend
      - test-frontend:
          requires:
            - build-frontend
            - build-backend
      - test-backend:
          requires:
            - build-frontend
            - build-backend

            