version: 2.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello
          command: |
            echo "Hello World"

  #build phase
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: cd ./frontend && npm i && npm run build 

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: cd ./backend && npm i && npm run build

  #test phase
  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: cd ./frontend && npm i && npm install --save-dev jest-junit  && npm run test --ci --runInBand --reporters=default --reporters=jest-junit
          environment
            - JEST_JUNIT_OUTPUT_DIR: ./frontend/reports/junit/
      - store_test_results:
          path: ./frontend/reports/junit/
      - store_artifacts:
          path: ./frontend/reports/junit

  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: cd ./backend && npm i && npm install --save-dev jest-junit && npm run test --ci --runInBand --reporters=default --reporters=jest-junit
          environment
            - JEST_JUNIT_OUTPUT_DIR: ./backend/reports/junit/
      - store_test_results:
          path: ./backend/reports/junit/
      - store_artifacts:
          path: ./backend/reports/junit

workflows:
  default:
    jobs:
      - hello-world
      - build-frontend
      - build-backend
      - test-frontend:
          requires:
            - build-frontend
            - build-backend
      - test-backend:
          requires:
            - build-frontend
            - build-backend

            