version: 2.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello
          command: |
            echo "Hello World"

  #build phase
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: cd ./frontend && npm i && npm install --save-dev jest-junit && npm run build 

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: cd ./backend && npm i && npm install --save-dev jest-junit && npm run build

  #test phase
  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: cd ./frontend && npm run test && npm run test:e2e && npm run test:cov

  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: cd ./backend && npm run test && npm run test:e2e && npm run test:cov

reports:
  jest_reports:
    files:
      - "report.xml"
    file-format: JunitXml
    base-directory: ./

workflows:
  default:
    jobs:
      - hello-world
      - build-frontend
      - build-backend
      - test-frontend:
          requires:
            - build-frontend
            - build-backend
      - test-backend:
          requires:
            - build-frontend
            - build-backend

            