version: 2.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello
          command: |
            echo "Hello World"

  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      #- run: cd frontend
      - run: ls
      - run: npm i
      - run: npm run build
      base-directory: /frontend

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: cd backend
      - run: npm login
      - run: npm i
      - run: npm start

workflows:
  default:
    jobs:
      - hello-world
      - build-frontend
      - build-backend:
          requires: 
            - build-frontend 
