version: 2.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello
          command: |
            echo "Hello World"

  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: 
          name: build
          command: |
            cd frontend
            npm i
            npm start
            npm run build

  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: 
          name: build
          command: |
            cd backend
            npm login
            npm i
            npm start

workflows:
  default:
    jobs:
      - hello-world
      - build-frontend
      - build-backend
