
- name: Compress directory
  archive:
    path: ../../backend
    dest: ./roles/copy-backend/files/backend.tar.gz


- name: Extract directory on ec2 instance
  become: true
  unarchive:
    src: backend.tar.gz
    dest: /home/ubuntu